# Generated by Django 3.1.3 on 2020-11-17 08:55

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.get_avatar_image_path),
        ),
    ]
