# Generated by Django 3.1.3 on 2020-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments_feed', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
